name: Build and create release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Restore dependencies
        run: dotnet restore
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish project
        run: dotnet publish --no-restore -c Release -p:PublishSingleFile=true --self-contained false -r win-x64
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
      - name: Zip build
        uses: vimtor/action-zip@v1
        with:
          files: "JKMP.Patcher/bin/Release/net5.0/win-x64/publish/"
          dest: "Build.zip"
          recursive: true
      - name: Publish release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            Build.zip
            LICENSE
          prerelease: true
          tag: latest