name: Build and create release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Restore dependencies
        run: dotnet restore
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish project
        run: dotnet publish --no-restore -c Release -r win
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
      - name: Package artifact
        uses: vimtor/action-zip@v1
        with:
          files: "JKMP.Patcher/bin/Release/net462/win/JKMP.Patcher.exe"
          dest: "JKMP.Patcher.zip"
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: Modular release
          artifacts: JKMP.Patcher.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          generateReleaseNotes: true