name: Build and create release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Restore dependencies
        run: dotnet restore
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build project
        run: dotnet build --no-restore -c Release
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
      - name: Zip build
        uses: TheDoctor0/zip-release@0.6.0
        with:
          type: "zip"
          filename: "Build.zip"
          path: "JKMP.Patcher/bin/Release/net5.0/**/*"
          exclusions: "**/*.pdb"
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Build.zip,LICENSE"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          tag: latest
          commit: ${{ github.sha }}
          name: Automated build